
import React from 'react';
import { InvestorPackageEntity } from '../domain/investor_package.entity';

interface Props {
  pkg: InvestorPackageEntity;
}

export const InvestorDeckPreview: React.FC<Props> = ({ pkg }) => {
  return (
    <div className="bg-white text-slate-900 rounded-xl shadow-2xl overflow-hidden max-w-4xl mx-auto border border-slate-200">
      
      {/* Cover Slide */}
      <div className="bg-slate-900 text-white p-12 text-center relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/20 rounded-full blur-3xl -mr-20 -mt-20"></div>
        <div className="relative z-10">
            <div className="uppercase tracking-widest text-xs font-bold text-indigo-400 mb-4">Confidential Investment Memo</div>
            <h1 className="text-4xl md:text-5xl font-bold font-display mb-6">{pkg.headlines[0]}</h1>
            <div className="flex justify-center gap-6">
                {pkg.keyMetrics.slice(0,3).map((m, i) => (
                    <div key={i} className="text-center">
                        <div className="text-2xl font-mono font-bold text-emerald-400">{m.value}</div>
                        <div className="text-[10px] text-slate-400 uppercase">{m.label}</div>
                    </div>
                ))}
            </div>
        </div>
      </div>

      {/* Narrative Section */}
      <div className="p-10 border-b border-slate-100">
          <div className="prose prose-slate max-w-none">
              <h3 className="text-2xl font-bold font-display text-slate-900 mb-4">Executive Summary</h3>
              <div className="text-slate-600 leading-relaxed whitespace-pre-wrap font-light text-lg">
                  {pkg.narrativeMarkdown}
              </div>
          </div>
      </div>

      {/* Outline / Slides Preview Grid */}
      <div className="p-10 bg-slate-50">
          <h3 className="text-xl font-bold font-display text-slate-900 mb-6">Deck Structure</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {pkg.deckOutline.map((slide, i) => (
                  <div key={slide.id} className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                      <div className="flex justify-between items-start mb-3">
                          <h4 className="font-bold text-slate-800">
                              <span className="text-indigo-500 mr-2">{i+1}.</span>
                              {slide.slideTitle}
                          </h4>
                      </div>
                      <ul className="space-y-2 mb-4">
                          {slide.keyPoints.map((pt, j) => (
                              <li key={j} className="text-sm text-slate-600 flex items-start gap-2">
                                  <span className="text-slate-300 text-[10px] mt-1">●</span>
                                  {pt}
                              </li>
                          ))}
                      </ul>
                      {slide.visualSuggestion && (
                          <div className="text-xs text-slate-400 italic bg-slate-50 p-2 rounded border border-slate-100">
                              🎨 Visual: {slide.visualSuggestion}
                          </div>
                      )}
                  </div>
              ))}
          </div>
      </div>

      {/* FAQ Section */}
      <div className="p-10 border-t border-slate-200">
          <h3 className="text-xl font-bold font-display text-slate-900 mb-6">Investor FAQ</h3>
          <div className="space-y-4">
              {pkg.faq.map(item => (
                  <div key={item.id} className="border-b border-slate-100 last:border-0 pb-4 last:pb-0">
                      <h5 className="font-bold text-slate-800 text-sm mb-2 flex items-center gap-2">
                          <span className="text-indigo-500">Q:</span> {item.question}
                      </h5>
                      <p className="text-sm text-slate-600 leading-relaxed pl-6">
                          {item.answer}
                      </p>
                  </div>
              ))}
          </div>
      </div>

      {/* Footer */}
      <div className="bg-slate-50 p-6 text-center text-xs text-slate-400 border-t border-slate-200">
          Generated by PropertyDEX Enterprise • {new Date(pkg.createdAt).toLocaleDateString()}
      </div>

    </div>
  );
};
