
export type DealStage = 'overview' | 'asset' | 'financial' | 'thesis' | 'audit' | 'package' | 'export';

export interface DataRoomProject {
  id: string;
  updatedAt: string;
  
  // 1. Deal Overview
  overview: {
    dealName: string;
    assetType: string; // Real Estate, Debt, etc.
    dealGoal: 'Liquidity' | 'Capital Raise' | 'Refinancing';
    targetRaise: number;
    minTicket: number;
    spvStructure: string;
  };

  // 2. Asset Intelligence
  asset: {
    description: string;
    location: string;
    specs: Record<string, string>; // e.g. { "sqft": "10000", "units": "20" }
    images: string[];
    marketHighlights: string[]; // Generated by AI
    assetCondition: 'Ground Up' | 'Value Add' | 'Stabilized';
  };

  // 3. Financial Story
  financials: {
    valuation: number;
    noi: number;
    capRate: number;
    irr: number;
    cashOnCash: number;
    proFormaHtml: string; // Table content
    narrative: string; // AI Generated story
  };

  // 4. Investment Thesis
  thesis: {
    coreThesis: string;
    valueDrivers: string[];
    risks: string[];
    mitigations: string[];
    sponsorTrackRecord: string;
  };

  // 5. Risk Audit
  audit: {
    score: number; // 0-100
    flags: { area: string; issue: string; severity: 'low'|'medium'|'high' }[];
    status: 'Pending' | 'Passed' | 'Failed';
  };

  // 6. Package Builder
  package: {
    deckSlides: { title: string; content: string }[];
    memoHtml: string;
    faq: { q: string; a: string }[];
  };

  // 7. Export
  sync: {
    provider: 'Securitize' | 'Tokeny' | 'Fleap' | 'Blocksquare' | 'Manual';
    status: 'Idle' | 'Syncing' | 'Live';
    publicLink?: string;
  };
}

export const INITIAL_DATA_ROOM: DataRoomProject = {
  id: 'new',
  updatedAt: new Date().toISOString(),
  overview: { dealName: '', assetType: 'Real Estate', dealGoal: 'Capital Raise', targetRaise: 0, minTicket: 1000, spvStructure: 'LLC' },
  asset: { description: '', location: '', specs: {}, images: [], marketHighlights: [], assetCondition: 'Stabilized' },
  financials: { valuation: 0, noi: 0, capRate: 0, irr: 0, cashOnCash: 0, proFormaHtml: '', narrative: '' },
  thesis: { coreThesis: '', valueDrivers: [], risks: [], mitigations: [], sponsorTrackRecord: '' },
  audit: { score: 0, flags: [], status: 'Pending' },
  package: { deckSlides: [], memoHtml: '', faq: [] },
  sync: { provider: 'Manual', status: 'Idle' }
};
